---
# =============================================================================
# Dependabot Configuration
# =============================================================================

version: 2

updates:
  # Git Submodule dependencies
  # ===========================================================================

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-gitsubmodule"
      include: "scope"
    labels:
      - "dependencies"
      - "gitsubmodule"

  # GitHub Actions dependencies
  # ===========================================================================

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  # NPM dependencies
  # ===========================================================================

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "npm"
    labels:
      - "dependencies"
      - "npm"

  # Docker dependencies
  # ===========================================================================

  - package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-docker"
    labels:
      - "dependencies"
      - "docker"

  # devContainer dependencies
  # ===========================================================================

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-devcontainer"
    labels:
      - "dependencies"
      - "devcontainer"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-devcontainer"
    labels:
      - "dependencies"
      - "devcontainer"

  # PIP dependencies
  # ===========================================================================

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
    assignees:
      - "vanvianen"
    versioning-strategy: increase
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "pytest*"
          - "black"
          - "isort"
          - "flake8*"
          - "pylint"
          - "mypy"
          - "bandit*"
          - "coverage"
          - "sphinx*"
          - "tox"
          - "pre-commit"
      security-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
