[metadata]
name = bearing
version = attr: bearing.__version__
author = Lars van Vianen
author_email = lars@vianen.com
description = Spatial Computing Framework
long_description = file: README.md
long_description_content_type = text/markdown
license = LicenseRef-Proprietary
license_files = LICENSE
classifiers =
    Private :: Do Not Upload
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Natural Language :: English
    Operating System :: OS Independent
    Programming Language :: Python :: 3 :: Only

[options]
package_dir =
    =src
packages = find:
include_package_data = True
zip_safe = True
python_requires = >=3.11

[options.packages.find]
where = src
exclude =
    build*
    dist*
    docs*
    tst*
    *.tst
    *.tst.*
    tools*
    examples*
